In [1]:
import numpy as np

In [5]:
a = np.array([[1,2,3],[5,6,7]])
print(a)
print()
b = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = "int64")
print(b)

[[1 2 3]
 [5 6 7]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
# Getting dimension we use

a.ndim
# b.ndim

2

In [4]:
# getting shape (m,n)

# a.shape
b.shape

(3, 3)

In [5]:
# getting datatype : int32, int16, int8
b.dtype

dtype('int64')

In [6]:
# getting the number of byes we use the 

b.itemsize

8

# Array operations

In [7]:
# Accessing the array items a[r,c]

print(a[0,0]) # element at o,o
print(a[0,:]) # Elements  at row 0
print(a[:,2]) # Elements at col 2
print(a[:,0::2])

1
[1 2 3]
[3 7]
[[1 3]
 [5 7]]


In [8]:
# updattion

a[0,0] = 10
print(a)

a[0,:] = [1,2,3]
print(a)

[[10  2  3]
 [ 5  6  7]]
[[1 2 3]
 [5 6 7]]


In [5]:
# 3D

arr = np.array(
    [
        [
            [1, 2], [3, 4]
        ], 
        [
            [8, 7], [6, 5]
        ]
    ]
)
print(arr)

[[[1 2]
  [3 4]]

 [[8 7]
  [6 5]]]


In [10]:
print(arr[0,0,0])
print(arr[0,1,1])
print(arr[1,0,1])
print(arr[0,:,:])
print(arr[0,1,:])
print(arr[:,1,1])

1
4
7
[[1 2]
 [3 4]]
[3 4]
[4 5]


In [11]:
arr[:,0,:] = [[0,0],[0,0]]
print(arr)

[[[0 0]
  [3 4]]

 [[0 0]
  [6 5]]]


# initailising

In [12]:
TwoByTwo = np.zeros((2,2))
print(TwoByTwo)

[[0. 0.]
 [0. 0.]]


In [13]:
TByT = np.ones((3,3), dtype = "int16")
print(TByT)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [6]:
FByF = np.full([4,4,2], 45)
print(FByF)

[[[45 45]
  [45 45]
  [45 45]
  [45 45]]

 [[45 45]
  [45 45]
  [45 45]
  [45 45]]

 [[45 45]
  [45 45]
  [45 45]
  [45 45]]

 [[45 45]
  [45 45]
  [45 45]
  [45 45]]]


In [26]:
np.full_like(a,4) 
# np.full(a.shape, 4) jst same as above

array([[4, 4, 4],
       [4, 4, 4]])

In [8]:
# Random decimal number in the array

np.random.rand(2,2)
# np.random.random_sample(a.shape)

array([[0.49140411, 0.87829782],
       [0.82194688, 0.19336988]])

In [10]:
# Random integer number in an array
#                   start number, end number(Exculsive), dimension  
np.random.randint(3,10,size=(3,3))

array([[9, 7, 9],
       [4, 7, 6],
       [3, 3, 3]])

# Identity Matrix

In [24]:
np.identity(3) # specify the dimension

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# pattern

In [9]:
res = np.ones((5,5))

inner = np.zeros((3,3))
inner[1,1] = 9

res[1:-1, 1:-1] = inner
print(res)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Copying array

In [29]:
arr = np.array([1,2,3])
arr2 = arr
# arr2 and arr are pointed to the same memory location
# changes in any of them effects them both.
arr2

array([1, 2, 3])

In [14]:
arr3 = arr.copy()
arr3[0] = 34
arr3, arr

(array([34,  2,  3]), array([1, 2, 3]))

# Mathematics

In [30]:
arr + 2

array([3, 4, 5])

In [31]:
arr - 2

array([-1,  0,  1])

In [33]:
arr += 2
arr

array([3, 4, 5])

In [34]:
arr * 2

array([ 6,  8, 10])

In [35]:
arr / 2

array([1.5, 2. , 2.5])

In [36]:
arr + arr3

array([37,  6,  8])

In [38]:
arr ** 2

array([ 9, 16, 25], dtype=int32)

In [39]:
np.cos(arr)

# np.sin(arr)

# https://numpy.org/doc/stable/reference/routines.math.html

array([-0.9899925 , -0.65364362,  0.28366219])

# Linear Algebra (Matrix)

In [40]:
# https://numpy.org/doc/stable/reference/routines.linalg.html

In [8]:
matA = np.full((3,2), 3)

matB = np.full((2,3), 2)

res = np.matmul(matA, matB)

print(res)

[[12 12 12]
 [12 12 12]
 [12 12 12]]


In [3]:
# Determinant

idmat = np.identity(3)
np.linalg.det(idmat)

1.0

# Statistics

In [6]:
# np.max(matA, axis = 0)
# a = [[1 2 3]
#  [5 6 7]]
np.max(a, axis = 1)

array([3, 7])

In [9]:
np.min(matA)

3

In [13]:
np.sum(a, axis = 1)

array([ 6, 18])

# Re-organising

In [53]:
before = np.array([[1,2,3,4],[5,6,7,8]])

after = before.reshape(2,2,2)
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [55]:
# Verticlal Stacking

vstacking = np.vstack([before,before])
vstacking

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [58]:
for i in vstacking:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
1
2
3
4
5
6
7
8


In [59]:
hstacking = np.hstack([before,before])
hstacking

array([[1, 2, 3, 4, 1, 2, 3, 4],
       [5, 6, 7, 8, 5, 6, 7, 8]])

# loading data

In [11]:
aaaa = np.genfromtxt("numbers.txt", delimiter = "," ,dtype = "int16")
aaaa
# aaaa.astype("int16")

array([122,  34,   5,  77,  88], dtype=int16)

# Boolean masking and advanced indexing

In [68]:
aaaa > 77

array([ True, False, False, False,  True])

In [69]:
aaaa[aaaa > 77]

array([122,  88], dtype=int16)

In [14]:
# aaaa[[1,2]]

a[[1,0],[1,0]]

# a[[0,2,3],1:]

array([6, 1])

In [25]:
np.any(a > 5 , axis = 0)
# Checks whether any column value is greater than 5, then returns true
# a = [[1 2 3]
#  [5 6 7]]

array([False,  True,  True])

In [77]:
np.all(a > 5 , axis = 0)
# checks if all the values in the column have value greater than 5
# a = [[1 2 3]
#  [5 6 7]]

array([False, False, False])

In [80]:
((a > 5) & (a < 10))

# true for all values between 5 and 10

array([[False, False, False],
       [False,  True,  True]])

In [81]:
(~(a > 5) & (a < 10))

array([[ True,  True,  True],
       [ True, False, False]])

# Checking a specific row is in the numpy array

In [20]:
arr = np.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15],
                   [16, 17, 18, 19, 20]
                   ])


In [21]:
print([1, 2, 3, 4, 5] in arr.tolist())

True


In [22]:
print([16, 17, 20, 19, 18] in arr.tolist())

False


# How to Remove rows in Numpy array that contains non-numeric values?

In [21]:
n_arr = np.array([[10.5, 22.5, 3.8],
                  [41, np.nan, np.nan]])

In [23]:
print(n_arr[~np.isnan(n_arr).any(axis=1)])

[[10.5 22.5  3.8]]


In [27]:
print(n_arr[np.isfinite(n_arr).any(axis=1)])

[[10.5 22.5  3.8]
 [41.   nan  nan]]


# numpy.squeeze()
### numpy.squeeze() function is used when we want to remove single-dimensional entries from the shape of an array.

In [30]:
in_arr = np.array([[[2, 2, 2], [2, 2, 2]]])
# (1,2,3)
print ("Input array : ", in_arr) 

out_arr = np.squeeze(in_arr) 
# (2,3)
print ("output squeezed array : ", out_arr)

Input array :  [[[2 2 2]
  [2 2 2]]]
output squeezed array :  [[2 2 2]
 [2 2 2]]


#  Counting 

In [16]:
arr = np.array([[2, 8, 9, 4], 
                   [9, 4, 9, 4],
                   [4, 5, 9, 7],
                   [2, 9, 4, 3]])

# repr converts to string
output = repr(arr).count("9, 4")
print(output)

4


In [4]:
x = np.array([1,2,3,4,5,1,2,1,1,1, 10])
print(np.bincount(x).argmax())
# bincount gets the count of the elemtn and stores in the array
# argmax() gets the max value (Returns the indices of the maximum values along an axis.)

1


# Get the indices of maximum element in numpy array

In [17]:
arr = np.array([11, 12, 13, 14, 15, 16, 17, 15, 11, 12, 14, 15, 16, 17])

arr2D = np.array([[11, 12, 13],
                     [14, 15, 16],
                     [17, 15, 11],
                     [12, 14, 15]])

In [18]:
result = np.where(arr == np.max(arr))
result

(array([ 6, 13], dtype=int64),)

In [21]:
maxInRows = np.max(arr2D, axis=1)
maxInRows

array([13, 16, 17, 15])

In [46]:
res = np.where(arr2D == np.max(arr2D))
listOfCordinates = list(zip(res[0], res[1]))

for cord in listOfCordinates:
    print(cord)


(2, 0)


# Combining a one and a two-dimensional NumPy Array

In [56]:
num_1d = np.arange(2)
print("One dimensional array:")
print(num_1d)
  
num_2d = np.arange(12).reshape(6,2)
print("\nTwo dimensional array:")
print(num_2d)
  
# Combine 1-D and 2-D arrays and display
# their elements using numpy.nditer() 
for a, b in np.nditer([num_1d, num_2d]):
    print("%d:%d" % (a, b))

One dimensional array:
[0 1]

Two dimensional array:
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
0:0
1:1
0:2
1:3
0:4
1:5
0:6
1:7
0:8
1:9
0:10
1:11


# compare

In [57]:
an_array = np.array([[1, 2], [3, 4]])
another_array = np.array([[1, 2], [3, 4]])

comparison = an_array == another_array
equal_arrays = comparison.all()
  
print(equal_arrays)

True


# Numpy count_nonzero method

In [62]:
arr = [[0, 1, 2, 3, 4], [5, 0, 6, 0, 7]]
  
gfg = np.count_nonzero(arr)
gfg

7

In [63]:
#gives no. of rows along x-axis
print(np.size(arr, 0))
 
#gives no. of columns along y-axis
print(np.size(arr, 1))

2
5


# inverse a matrix 

In [3]:
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
  
print(np.linalg.inv(A))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


# count the frequency of unique values

In [5]:
ini_array = np.array([10, 20, 5,
                      10, 8, 20,
                      8, 9])
  
unique, frequency = np.unique(ini_array, 
                              return_counts = True)
print("Unique Values:", 
      unique)
  
print("Frequency Values:",
      frequency)

Unique Values: [ 5  8  9 10 20]
Frequency Values: [1 2 1 2 2]


# Filter out integers from float

In [6]:
ini_array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
 
print ("initial array : ", str(ini_array))
 
result = ini_array[ini_array != ini_array.astype(int)]
 
print ("final array", result)

initial array :  [1.  1.2 2.2 2.  3.  2. ]
final array [1.2 2.2]


# true division

In [7]:
x = np.arange(5)
  
print("Original array:",x)

rslt = np.true_divide(x, 4)
  
print("After the element-wise division:",rslt)

Original array: [0 1 2 3 4]
After the element-wise division: [0.   0.25 0.5  0.75 1.  ]


# absolute value of NumPy array

In [9]:
array = np.array([1, -2, 3])
  
print("Given array:\n", array)
  
rslt = np.absolute(array)
  
print("Absolute array:\n", rslt)

Given array:
 [ 1 -2  3]
Absolute array:
 [1 2 3]


# np.negative()

In [10]:
in_arr = np.array([[2, -7, 5], [-6, 2, 0]])
   
print ("Input array : ", in_arr) 
    
out_arr = np.negative(in_arr) 
print ("negative of array elements: ", out_arr) 

Input array :  [[ 2 -7  5]
 [-6  2  0]]
negative of array elements:  [[-2  7 -5]
 [ 6 -2  0]]


# np.sqrt()

In [13]:
arr1 = np.sqrt([1, 4, 9, 16]).astype("int16")
arr1

array([1, 2, 3, 4], dtype=int16)

# Rounding to the nearest integer

In [14]:
y = np.array([0.2, 0.3, 0.4, 0.5, 0.6, 0.7])
y = np.rint(y)
y

array([0., 0., 0., 0., 1., 1.])

# Median

In [21]:
x_odd = np.array([1, 2, 10 ,8, 3, 4, 5, 6, 7])
print("\nPrinting the Original array:")
print(x_odd)

med_odd = np.median(x_odd)
print("\nMedian of the array that contains \
odd no of elements:")
print(med_odd)


Printing the Original array:
[ 1  2 10  8  3  4  5  6  7]

Median of the array that contains odd no of elements:
5.0


# mean

In [22]:
Input = [np.array([1, 2, 3]),
         np.array([4, 5, 6]),
         np.array([7, 8, 9])]
  
# Output list initialization
Output = []
  
# using np.mean()
for i in range(len(Input)):
   Output.append(np.mean(Input[i]))
  
# Printing output
print(Output)

[2.0, 5.0, 8.0]


In [25]:
# Ignoring nan values

arr = np.array([[20, 15, 37], [47, 13, np.nan]])
   
print("Shape of array is", arr.shape)
   
print("Mean of array without using nanmean function:",
                                           np.mean(arr))
   
print("Using nanmean function:", np.nanmean(arr))

Shape of array is (2, 3)
Mean of array without using nanmean function: nan
Using nanmean function: 26.4


# Standard deviation

In [26]:
arr = [20, 2, 7, 1, 34]
  
print("arr : ", arr) 
print("std of arr : ", np.std(arr))
  
print ("\nMore precision with float32")
print("std of arr : ", np.std(arr, dtype = np.float32))
  
print ("\nMore accuracy with float64")
print("std of arr : ", np.std(arr, dtype = np.float64))

arr :  [20, 2, 7, 1, 34]
std of arr :  12.576167937809991

More precision with float32
std of arr :  12.576168

More accuracy with float64
std of arr :  12.576167937809991


# Polynomial

In [2]:
import numpy as np
  
# Constructing polynomial
p1 = np.poly1d([1, 2])
p2 = np.poly1d([4, 9, 5, 4])
  
print ("P1 : ", p1)
print ("\n p2 : \n", p2)
  
# Solve for x = 2
print ("\n\np1 at x = 2 : ", p1(2))
print ("p2 at x = 2 : ", p2(2))
  
# Finding Roots
print ("\n\nRoots of P1 : ", p1.r)
print ("Roots of P2 : ", p2.r)
  
# Finding Coefficients
print ("\n\nCoefficients of P1 : ", p1.c)
print ("Coefficients of P2 : ", p2.coeffs)
  
# Finding Order
print ("\n\nOrder / Degree of P1 : ", p1.o)
print ("Order / Degree of P2 : ", p2.order)

P1 :   
1 x + 2

 p2 : 
    3     2
4 x + 9 x + 5 x + 4


p1 at x = 2 :  4
p2 at x = 2 :  82


Roots of P1 :  [-2.]
Roots of P2 :  [-1.86738371+0.j         -0.19130814+0.70633545j -0.19130814-0.70633545j]


Coefficients of P1 :  [1 2]
Coefficients of P2 :  [4 9 5 4]


Order / Degree of P1 :  1
Order / Degree of P2 :  3


In [25]:
px = (5, -2, 5)
  
# g(x) = x +2
gx = (2, 1, 0)
  
# divide the polynomials
qx, rx = np.polydiv(px, gx)
  
# print the result
# quotiient
print(qx)
  
# remainder
print(rx)

[2.5]
[-4.5  5. ]


In [26]:
coeff = [1, 2, 1]
print(np.roots(coeff))

[-1.+6.68896751e-09j -1.-6.68896751e-09j]


# String Opertstions

In [28]:
arr = np.array(['Akash', 'Rohit', 'Ayush', 
                'Dhruv', 'Radhika'], dtype = str)
print("Original Array :")
print(arr)
  
# with the help of np.char.multiply()
# repeating the characters 3 times
new_array = np.char.multiply(arr, 3)
print("\nNew array :")
print(new_array)

Original Array :
['Akash' 'Rohit' 'Ayush' 'Dhruv' 'Radhika']

New array :
['AkashAkashAkash' 'RohitRohitRohit' 'AyushAyushAyush' 'DhruvDhruvDhruv'
 'RadhikaRadhikaRadhika']
